"""Company names for scanner universe and news ticker resolution."""

SYMBOL_NAMES: dict[str, str] = {
    # Tech
    "AAPL": "Apple Inc.", "MSFT": "Microsoft Corp.", "GOOGL": "Alphabet Inc.", "GOOG": "Alphabet Inc.",
    "AMZN": "Amazon.com Inc.", "NVDA": "NVIDIA Corp.", "META": "Meta Platforms", "TSLA": "Tesla Inc.",
    "AVGO": "Broadcom Inc.", "ORCL": "Oracle Corp.", "CRM": "Salesforce Inc.", "ADBE": "Adobe Inc.",
    "AMD": "Advanced Micro Devices", "INTC": "Intel Corp.", "CSCO": "Cisco Systems", "IBM": "IBM Corp.",
    "QCOM": "Qualcomm Inc.", "TXN": "Texas Instruments", "AMAT": "Applied Materials", "LRCX": "Lam Research",
    "KLAC": "KLA Corp.", "MU": "Micron Technology", "ADI": "Analog Devices", "PANW": "Palo Alto Networks",
    "CRWD": "CrowdStrike", "SNOW": "Snowflake Inc.", "DDOG": "Datadog Inc.", "NET": "Cloudflare Inc.",
    "PLTR": "Palantir Technologies", "COIN": "Coinbase Global", "NOW": "ServiceNow", "INTU": "Intuit Inc.",
    "SNPS": "Synopsys", "CDNS": "Cadence Design", "FTNT": "Fortinet", "ZS": "Zscaler", "TEAM": "Atlassian",
    "WDAY": "Workday", "HUBS": "HubSpot", "VEEV": "Veeva Systems", "ACN": "Accenture", "ADP": "ADP Inc.",
    "PAYX": "Paychex", "CTSH": "Cognizant", "INFY": "Infosys", "WIT": "Wipro",
    # Semis / hardware / ADRs
    "ASML": "ASML Holding", "TSM": "Taiwan Semiconductor", "ARM": "Arm Holdings", "MRVL": "Marvell Technology",
    "ON": "ON Semiconductor", "NXPI": "NXP Semiconductors", "MCHP": "Microchip Technology",
    "SWKS": "Skyworks Solutions", "QRVO": "Qorvo", "MPWR": "Monolithic Power", "ANET": "Arista Networks",
    "DELL": "Dell Technologies", "HPE": "Hewlett Packard Enterprise", "HPQ": "HP Inc.", "WDC": "Western Digital",
    "STX": "Seagate Technology", "NTAP": "NetApp", "GLW": "Corning", "KEYS": "Keysight Technologies",
    "SMCI": "Super Micro Computer",
    # Financials
    "BRK-B": "Berkshire Hathaway", "JPM": "JPMorgan Chase", "V": "Visa Inc.", "MA": "Mastercard Inc.",
    "BAC": "Bank of America", "WFC": "Wells Fargo", "GS": "Goldman Sachs", "MS": "Morgan Stanley",
    "C": "Citigroup Inc.", "AXP": "American Express", "BLK": "BlackRock Inc.", "SCHW": "Charles Schwab",
    "SPGI": "S&P Global", "MCO": "Moody's Corp.", "ICE": "Intercontinental Exchange", "CME": "CME Group",
    "PYPL": "PayPal Holdings", "SQ": "Block Inc.", "SOFI": "SoFi Technologies", "HOOD": "Robinhood Markets",
    "AFRM": "Affirm Holdings", "UPST": "Upstart Holdings", "COF": "Capital One", "USB": "U.S. Bancorp",
    "PNC": "PNC Financial", "TFC": "Truist Financial", "BK": "Bank of New York Mellon", "STT": "State Street",
    "MET": "MetLife", "PRU": "Prudential Financial", "AIG": "American International Group", "ALL": "Allstate",
    "FIS": "Fidelity National Information", "FI": "Fiserv", "GPN": "Global Payments", "TRU": "TransUnion",
    "NDAQ": "Nasdaq Inc.",
    # Healthcare
    "UNH": "UnitedHealth Group", "JNJ": "Johnson & Johnson", "LLY": "Eli Lilly", "MRK": "Merck & Co.",
    "ABBV": "AbbVie Inc.", "PFE": "Pfizer Inc.", "TMO": "Thermo Fisher", "ABT": "Abbott Laboratories",
    "DHR": "Danaher Corp.", "BMY": "Bristol-Myers Squibb", "AMGN": "Amgen Inc.", "GILD": "Gilead Sciences",
    "ISRG": "Intuitive Surgical", "VRTX": "Vertex Pharmaceuticals", "REGN": "Regeneron Pharmaceuticals",
    "CVS": "CVS Health", "ELV": "Elevance Health", "CI": "Cigna Group", "HUM": "Humana Inc.",
    "ZTS": "Zoetis Inc.", "MDT": "Medtronic", "SYK": "Stryker", "BSX": "Boston Scientific",
    "EW": "Edwards Lifesciences", "DXCM": "DexCom", "MRNA": "Moderna", "BIIB": "Biogen",
    "ILMN": "Illumina", "IDXX": "IDEXX Laboratories", "NVO": "Novo Nordisk", "AZN": "AstraZeneca",
    "GSK": "GSK plc", "SNY": "Sanofi", "TAK": "Takeda Pharmaceutical",
    # Consumer
    "WMT": "Walmart Inc.", "COST": "Costco Wholesale", "HD": "Home Depot", "LOW": "Lowe's Companies",
    "TGT": "Target Corp.", "TJX": "TJX Companies", "NKE": "Nike Inc.", "SBUX": "Starbucks Corp.",
    "MCD": "McDonald's Corp.", "DIS": "Walt Disney Co.", "NFLX": "Netflix Inc.", "BKNG": "Booking Holdings",
    "ABNB": "Airbnb Inc.", "UBER": "Uber Technologies", "MAR": "Marriott International",
    "CMG": "Chipotle Mexican Grill", "LULU": "Lululemon Athletica", "ROST": "Ross Stores",
    "PG": "Procter & Gamble", "KO": "Coca-Cola Co.", "PEP": "PepsiCo Inc.", "PM": "Philip Morris",
    "MO": "Altria Group", "CL": "Colgate-Palmolive", "EL": "Estée Lauder", "YUM": "Yum! Brands",
    "DPZ": "Domino's Pizza", "DRI": "Darden Restaurants", "ETSY": "Etsy Inc.", "CHWY": "Chewy Inc.",
    "DKNG": "DraftKings", "RBLX": "Roblox Corp.", "DASH": "DoorDash", "UL": "Unilever",
    "DEO": "Diageo", "BUD": "Anheuser-Busch InBev", "STZ": "Constellation Brands", "BF-B": "Brown-Forman",
    "MNST": "Monster Beverage", "KDP": "Keurig Dr Pepper", "GIS": "General Mills", "K": "Kellanova",
    "HSY": "Hershey", "MDLZ": "Mondelez International",
    # Luxury / autos / travel
    "RACE": "Ferrari N.V.", "TM": "Toyota Motor", "HMC": "Honda Motor", "STLA": "Stellantis",
    "F": "Ford Motor Co.", "GM": "General Motors", "RIVN": "Rivian Automotive", "LCID": "Lucid Group",
    "MBLY": "Mobileye", "APTV": "Aptiv", "CCL": "Carnival Corp.", "RCL": "Royal Caribbean",
    "NCLH": "Norwegian Cruise Line", "DAL": "Delta Air Lines", "UAL": "United Airlines",
    "AAL": "American Airlines", "LUV": "Southwest Airlines", "ALK": "Alaska Air", "EXPE": "Expedia Group",
    "LYFT": "Lyft Inc.",
    # Energy / materials
    "XOM": "Exxon Mobil", "CVX": "Chevron Corp.", "COP": "ConocoPhillips", "SLB": "Schlumberger",
    "EOG": "EOG Resources", "OXY": "Occidental Petroleum", "MPC": "Marathon Petroleum", "PSX": "Phillips 66",
    "FCX": "Freeport-McMoRan", "NEM": "Newmont Corp.", "LIN": "Linde plc", "APD": "Air Products",
    "SHW": "Sherwin-Williams", "ECL": "Ecolab Inc.", "DOW": "Dow Inc.", "DD": "DuPont",
    "NUE": "Nucor", "STLD": "Steel Dynamics", "VMC": "Vulcan Materials", "MLM": "Martin Marietta",
    "BP": "BP plc", "SHEL": "Shell plc", "TTE": "TotalEnergies", "EQNR": "Equinor", "CNQ": "Canadian Natural",
    "SU": "Suncor Energy", "ENB": "Enbridge", "TRP": "TC Energy", "BHP": "BHP Group", "RIO": "Rio Tinto",
    "VALE": "Vale S.A.", "SCCO": "Southern Copper", "AA": "Alcoa", "X": "United States Steel", "CLF": "Cleveland-Cliffs",
    # Industrials
    "CAT": "Caterpillar Inc.", "DE": "Deere & Co.", "HON": "Honeywell International", "UPS": "United Parcel Service",
    "RTX": "RTX Corp.", "LMT": "Lockheed Martin", "BA": "Boeing Co.", "GE": "GE Aerospace", "MMM": "3M Company",
    "UNP": "Union Pacific", "FDX": "FedEx Corp.", "CSX": "CSX Corp.", "NSC": "Norfolk Southern",
    "WM": "Waste Management", "RSG": "Republic Services", "EMR": "Emerson Electric", "ITW": "Illinois Tool Works",
    "PH": "Parker-Hannifin", "ROK": "Rockwell Automation", "CARR": "Carrier Global", "OTIS": "Otis Worldwide",
    "GD": "General Dynamics", "NOC": "Northrop Grumman", "LHX": "L3Harris", "TDG": "TransDigm",
    "HEI": "HEICO", "AXON": "Axon Enterprise", "CNI": "Canadian National Railway", "CP": "Canadian Pacific Kansas City",
    "URI": "United Rentals", "PCAR": "PACCAR", "CMI": "Cummins",
    # Telecom / utilities
    "T": "AT&T Inc.", "VZ": "Verizon Communications", "TMUS": "T-Mobile US", "CMCSA": "Comcast Corp.",
    "CHTR": "Charter Communications", "NEE": "NextEra Energy", "DUK": "Duke Energy", "SO": "Southern Company",
    "AEP": "American Electric Power", "SRE": "Sempra", "EXC": "Exelon", "XEL": "Xcel Energy",
    "D": "Dominion Energy", "PCG": "PG&E Corp.", "ED": "Consolidated Edison", "WEC": "WEC Energy", "ES": "Eversource Energy",
    # Growth / crypto / clean energy
    "MARA": "MARA Holdings", "RIOT": "Riot Platforms", "ENPH": "Enphase Energy", "FSLR": "First Solar",
    "RUN": "Sunrun", "PLUG": "Plug Power", "CHPT": "ChargePoint", "TTD": "The Trade Desk",
    "PINS": "Pinterest", "SNAP": "Snap Inc.", "ROKU": "Roku Inc.", "SPOT": "Spotify", "ZM": "Zoom Video",
    "SHOP": "Shopify", "SE": "Sea Limited", "MELI": "MercadoLibre", "NU": "Nu Holdings", "GRAB": "Grab Holdings",
    # Asia ADRs
    "BABA": "Alibaba Group", "JD": "JD.com", "PDD": "PDD Holdings", "BIDU": "Baidu", "NIO": "NIO Inc.",
    "XPEV": "XPeng", "LI": "Li Auto", "TME": "Tencent Music", "BILI": "Bilibili", "NTES": "NetEase",
    "SONY": "Sony Group",
    # Europe / UK / Canada / LatAm
    "SAP": "SAP SE", "SIEGY": "Siemens", "PHG": "Philips", "ABB": "ABB Ltd", "NOK": "Nokia",
    "ERIC": "Ericsson", "RELX": "RELX plc", "HSBC": "HSBC Holdings", "BCS": "Barclays", "DB": "Deutsche Bank",
    "ING": "ING Groep", "SAN": "Banco Santander", "BBVA": "Banco Bilbao Vizcaya", "UBS": "UBS Group",
    "RY": "Royal Bank of Canada", "TD": "Toronto-Dominion Bank", "BNS": "Bank of Nova Scotia",
    "BMO": "Bank of Montreal", "CM": "Canadian Imperial Bank", "IBN": "ICICI Bank", "HDB": "HDFC Bank",
    "ITUB": "Itaú Unibanco", "PBR": "Petróleo Brasileiro", "BBD": "Banco Bradesco",
    # REITs / ETFs
    "PLD": "Prologis Inc.", "AMT": "American Tower", "EQIX": "Equinix Inc.", "SPG": "Simon Property",
    "O": "Realty Income", "PSA": "Public Storage", "WELL": "Welltower", "DLR": "Digital Realty",
    "VICI": "VICI Properties", "AVB": "AvalonBay Communities",
    "SPY": "SPDR S&P 500 ETF", "QQQ": "Invesco QQQ Trust", "IWM": "iShares Russell 2000", "DIA": "SPDR Dow Jones",
    "VTI": "Vanguard Total Stock Market", "VOO": "Vanguard S&P 500", "EFA": "iShares MSCI EAFE",
    "EEM": "iShares MSCI Emerging Markets", "GLD": "SPDR Gold Shares", "SLV": "iShares Silver Trust",
    "TLT": "iShares 20+ Year Treasury", "HYG": "iShares iBoxx High Yield",
    # Extra large/mid
    "CRH": "CRH plc", "ETN": "Eaton Corp.", "TT": "Trane Technologies", "JCI": "Johnson Controls",
    "IR": "Ingersoll Rand", "AME": "AMETEK", "FAST": "Fastenal", "GWW": "W.W. Grainger",
    "CTAS": "Cintas", "ODFL": "Old Dominion Freight", "CPRT": "Copart", "ORLY": "O'Reilly Automotive",
    "AZO": "AutoZone", "AAP": "Advance Auto Parts", "BBY": "Best Buy", "DG": "Dollar General",
    "DLTR": "Dollar Tree", "KR": "Kroger", "SYY": "Sysco", "MCK": "McKesson", "CAH": "Cardinal Health",
    "COR": "Cencora", "WBA": "Walgreens Boots Alliance",
}

KNOWN_TICKERS: frozenset[str] = frozenset(SYMBOL_NAMES.keys())
