"""Company names for scanner universe and news ticker resolution."""

SYMBOL_NAMES: dict[str, str] = {
    "AAPL": "Apple Inc.", "MSFT": "Microsoft Corp.", "GOOGL": "Alphabet Inc.", "GOOG": "Alphabet Inc.",
    "AMZN": "Amazon.com Inc.", "NVDA": "NVIDIA Corp.", "META": "Meta Platforms", "TSLA": "Tesla Inc.",
    "AVGO": "Broadcom Inc.", "ORCL": "Oracle Corp.", "CRM": "Salesforce Inc.", "ADBE": "Adobe Inc.",
    "AMD": "Advanced Micro Devices", "INTC": "Intel Corp.", "CSCO": "Cisco Systems", "IBM": "IBM Corp.",
    "QCOM": "Qualcomm Inc.", "TXN": "Texas Instruments", "AMAT": "Applied Materials", "LRCX": "Lam Research",
    "KLAC": "KLA Corp.", "MU": "Micron Technology", "ADI": "Analog Devices", "PANW": "Palo Alto Networks",
    "CRWD": "CrowdStrike", "SNOW": "Snowflake Inc.", "DDOG": "Datadog Inc.", "NET": "Cloudflare Inc.",
    "PLTR": "Palantir Technologies", "COIN": "Coinbase Global", "BRK-B": "Berkshire Hathaway",
    "JPM": "JPMorgan Chase", "V": "Visa Inc.", "MA": "Mastercard Inc.", "BAC": "Bank of America",
    "WFC": "Wells Fargo", "GS": "Goldman Sachs", "MS": "Morgan Stanley", "C": "Citigroup Inc.",
    "AXP": "American Express", "BLK": "BlackRock Inc.", "SCHW": "Charles Schwab", "SPGI": "S&P Global",
    "MCO": "Moody's Corp.", "ICE": "Intercontinental Exchange", "CME": "CME Group", "PYPL": "PayPal Holdings",
    "SOFI": "SoFi Technologies", "UNH": "UnitedHealth Group", "JNJ": "Johnson & Johnson", "LLY": "Eli Lilly",
    "MRK": "Merck & Co.", "ABBV": "AbbVie Inc.", "PFE": "Pfizer Inc.", "TMO": "Thermo Fisher",
    "ABT": "Abbott Laboratories", "DHR": "Danaher Corp.", "BMY": "Bristol-Myers Squibb", "AMGN": "Amgen Inc.",
    "GILD": "Gilead Sciences", "ISRG": "Intuitive Surgical", "VRTX": "Vertex Pharmaceuticals",
    "REGN": "Regeneron Pharmaceuticals", "CVS": "CVS Health", "ELV": "Elevance Health", "CI": "Cigna Group",
    "HUM": "Humana Inc.", "ZTS": "Zoetis Inc.", "WMT": "Walmart Inc.", "COST": "Costco Wholesale",
    "HD": "Home Depot", "LOW": "Lowe's Companies", "TGT": "Target Corp.", "TJX": "TJX Companies",
    "NKE": "Nike Inc.", "SBUX": "Starbucks Corp.", "MCD": "McDonald's Corp.", "DIS": "Walt Disney Co.",
    "NFLX": "Netflix Inc.", "BKNG": "Booking Holdings", "ABNB": "Airbnb Inc.", "UBER": "Uber Technologies",
    "MAR": "Marriott International", "CMG": "Chipotle Mexican Grill", "LULU": "Lululemon Athletica",
    "ROST": "Ross Stores", "PG": "Procter & Gamble", "KO": "Coca-Cola Co.", "PEP": "PepsiCo Inc.",
    "PM": "Philip Morris", "MO": "Altria Group", "CL": "Colgate-Palmolive", "EL": "Estée Lauder",
    "XOM": "Exxon Mobil", "CVX": "Chevron Corp.", "COP": "ConocoPhillips", "SLB": "Schlumberger",
    "EOG": "EOG Resources", "OXY": "Occidental Petroleum", "MPC": "Marathon Petroleum", "PSX": "Phillips 66",
    "FCX": "Freeport-McMoRan", "NEM": "Newmont Corp.", "LIN": "Linde plc", "APD": "Air Products",
    "SHW": "Sherwin-Williams", "ECL": "Ecolab Inc.", "CAT": "Caterpillar Inc.", "DE": "Deere & Co.",
    "HON": "Honeywell International", "UPS": "United Parcel Service", "RTX": "RTX Corp.", "LMT": "Lockheed Martin",
    "BA": "Boeing Co.", "GE": "GE Aerospace", "MMM": "3M Company", "UNP": "Union Pacific", "FDX": "FedEx Corp.",
    "T": "AT&T Inc.", "VZ": "Verizon Communications", "TMUS": "T-Mobile US", "CMCSA": "Comcast Corp.",
    "NEE": "NextEra Energy", "DUK": "Duke Energy", "SO": "Southern Company", "F": "Ford Motor Co.",
    "GM": "General Motors", "RIVN": "Rivian Automotive", "LCID": "Lucid Group", "MARA": "MARA Holdings",
    "RIOT": "Riot Platforms", "SMCI": "Super Micro Computer", "ARM": "Arm Holdings", "MRVL": "Marvell Technology",
    "ON": "ON Semiconductor", "PLD": "Prologis Inc.", "AMT": "American Tower", "EQIX": "Equinix Inc.",
    "SPY": "SPDR S&P 500 ETF", "QQQ": "Invesco QQQ Trust", "DELL": "Dell Technologies", "SQ": "Block Inc.",
}

KNOWN_TICKERS: frozenset[str] = frozenset(SYMBOL_NAMES.keys())
