/** Ticker + company-name map synced from scanner universe. Auto-generated — do not hand-edit. */

export const SYMBOL_NAMES: Record<string, string> = {
  "AA": "Alcoa",
  "AAL": "American Airlines",
  "AAP": "Advance Auto Parts",
  "AAPL": "Apple Inc.",
  "ABB": "ABB Ltd",
  "ABBV": "AbbVie Inc.",
  "ABNB": "Airbnb Inc.",
  "ABT": "Abbott Laboratories",
  "ACN": "Accenture",
  "ADBE": "Adobe Inc.",
  "ADI": "Analog Devices",
  "ADP": "ADP Inc.",
  "AEP": "American Electric Power",
  "AFRM": "Affirm Holdings",
  "AIG": "American International Group",
  "ALK": "Alaska Air",
  "ALL": "Allstate",
  "AMAT": "Applied Materials",
  "AMD": "Advanced Micro Devices",
  "AME": "AMETEK",
  "AMGN": "Amgen Inc.",
  "AMT": "American Tower",
  "AMZN": "Amazon.com Inc.",
  "ANET": "Arista Networks",
  "APD": "Air Products",
  "APTV": "Aptiv",
  "ARM": "Arm Holdings",
  "ASML": "ASML Holding",
  "AVB": "AvalonBay Communities",
  "AVGO": "Broadcom Inc.",
  "AXON": "Axon Enterprise",
  "AXP": "American Express",
  "AZN": "AstraZeneca",
  "AZO": "AutoZone",
  "BA": "Boeing Co.",
  "BABA": "Alibaba Group",
  "BAC": "Bank of America",
  "BBD": "Banco Bradesco",
  "BBVA": "Banco Bilbao Vizcaya",
  "BBY": "Best Buy",
  "BCS": "Barclays",
  "BF-B": "Brown-Forman",
  "BHP": "BHP Group",
  "BIDU": "Baidu",
  "BIIB": "Biogen",
  "BILI": "Bilibili",
  "BK": "Bank of New York Mellon",
  "BKNG": "Booking Holdings",
  "BLK": "BlackRock Inc.",
  "BMO": "Bank of Montreal",
  "BMY": "Bristol-Myers Squibb",
  "BNS": "Bank of Nova Scotia",
  "BP": "BP plc",
  "BRK-B": "Berkshire Hathaway",
  "BSX": "Boston Scientific",
  "BUD": "Anheuser-Busch InBev",
  "C": "Citigroup Inc.",
  "CAH": "Cardinal Health",
  "CARR": "Carrier Global",
  "CAT": "Caterpillar Inc.",
  "CCL": "Carnival Corp.",
  "CDNS": "Cadence Design Systems",
  "CHPT": "ChargePoint",
  "CHTR": "Charter Communications",
  "CHWY": "Chewy Inc.",
  "CI": "Cigna Group",
  "CL": "Colgate-Palmolive",
  "CLF": "Cleveland-Cliffs",
  "CM": "Canadian Imperial Bank",
  "CMCSA": "Comcast Corp.",
  "CME": "CME Group",
  "CMG": "Chipotle Mexican Grill",
  "CMI": "Cummins",
  "CNI": "Canadian National Railway",
  "CNQ": "Canadian Natural",
  "COF": "Capital One",
  "COIN": "Coinbase Global",
  "COP": "ConocoPhillips",
  "COR": "Cencora",
  "COST": "Costco Wholesale",
  "CP": "Canadian Pacific Kansas City",
  "CPRT": "Copart",
  "CRH": "CRH plc",
  "CRM": "Salesforce Inc.",
  "CRWD": "CrowdStrike",
  "CSCO": "Cisco Systems",
  "CSX": "CSX Corp.",
  "CTAS": "Cintas",
  "CTSH": "Cognizant",
  "CVS": "CVS Health",
  "CVX": "Chevron Corp.",
  "D": "Dominion Energy",
  "DAL": "Delta Air Lines",
  "DASH": "DoorDash",
  "DB": "Deutsche Bank",
  "DD": "DuPont",
  "DDOG": "Datadog Inc.",
  "DE": "Deere & Co.",
  "DELL": "Dell Technologies",
  "DEO": "Diageo",
  "DG": "Dollar General",
  "DHR": "Danaher Corp.",
  "DIA": "SPDR Dow Jones",
  "DIS": "Walt Disney Co.",
  "DKNG": "DraftKings",
  "DLR": "Digital Realty",
  "DLTR": "Dollar Tree",
  "DOW": "Dow Inc.",
  "DPZ": "Domino's Pizza",
  "DRI": "Darden Restaurants",
  "DUK": "Duke Energy",
  "DXCM": "DexCom",
  "ECL": "Ecolab Inc.",
  "ED": "Consolidated Edison",
  "EEM": "iShares MSCI Emerging Markets",
  "EFA": "iShares MSCI EAFE",
  "EL": "Est\u00e9e Lauder",
  "ELV": "Elevance Health",
  "EMR": "Emerson Electric",
  "ENB": "Enbridge",
  "ENPH": "Enphase Energy",
  "EOG": "EOG Resources",
  "EQIX": "Equinix Inc.",
  "EQNR": "Equinor",
  "ERIC": "Ericsson",
  "ES": "Eversource Energy",
  "ETN": "Eaton Corp.",
  "ETSY": "Etsy Inc.",
  "EW": "Edwards Lifesciences",
  "EXC": "Exelon",
  "EXPE": "Expedia Group",
  "F": "Ford Motor Co.",
  "FAST": "Fastenal",
  "FCX": "Freeport-McMoRan",
  "FDX": "FedEx Corp.",
  "FI": "Fiserv",
  "FIS": "Fidelity National Information",
  "FSLR": "First Solar",
  "FTNT": "Fortinet Inc.",
  "GD": "General Dynamics",
  "GE": "GE Aerospace",
  "GILD": "Gilead Sciences",
  "GIS": "General Mills",
  "GLD": "SPDR Gold Shares",
  "GLW": "Corning",
  "GM": "General Motors",
  "GOOG": "Alphabet Inc.",
  "GOOGL": "Alphabet Inc.",
  "GPN": "Global Payments",
  "GRAB": "Grab Holdings",
  "GS": "Goldman Sachs",
  "GSK": "GSK plc",
  "GWW": "W.W. Grainger",
  "HD": "Home Depot",
  "HDB": "HDFC Bank",
  "HEI": "HEICO",
  "HMC": "Honda Motor",
  "HON": "Honeywell International",
  "HOOD": "Robinhood Markets",
  "HPE": "Hewlett Packard Enterprise",
  "HPQ": "HP Inc.",
  "HSBC": "HSBC Holdings",
  "HSY": "Hershey",
  "HUBS": "HubSpot",
  "HUM": "Humana Inc.",
  "HYG": "iShares iBoxx High Yield",
  "IBM": "IBM Corp.",
  "IBN": "ICICI Bank",
  "ICE": "Intercontinental Exchange",
  "IDXX": "IDEXX Laboratories",
  "ILMN": "Illumina",
  "INFY": "Infosys",
  "ING": "ING Groep",
  "INTC": "Intel Corp.",
  "INTU": "Intuit Inc.",
  "IR": "Ingersoll Rand",
  "ISRG": "Intuitive Surgical",
  "ITUB": "Ita\u00fa Unibanco",
  "ITW": "Illinois Tool Works",
  "IWM": "iShares Russell 2000",
  "JCI": "Johnson Controls",
  "JD": "JD.com",
  "JNJ": "Johnson & Johnson",
  "JPM": "JPMorgan Chase",
  "K": "Kellanova",
  "KDP": "Keurig Dr Pepper",
  "KEYS": "Keysight Technologies",
  "KLAC": "KLA Corp.",
  "KO": "Coca-Cola Co.",
  "KR": "Kroger",
  "LCID": "Lucid Group",
  "LHX": "L3Harris",
  "LI": "Li Auto",
  "LIN": "Linde plc",
  "LLY": "Eli Lilly",
  "LMT": "Lockheed Martin",
  "LOW": "Lowe's Companies",
  "LRCX": "Lam Research",
  "LULU": "Lululemon Athletica",
  "LUV": "Southwest Airlines",
  "LYFT": "Lyft Inc.",
  "MA": "Mastercard Inc.",
  "MAR": "Marriott International",
  "MARA": "MARA Holdings",
  "MBLY": "Mobileye",
  "MCD": "McDonald's Corp.",
  "MCHP": "Microchip Technology",
  "MCK": "McKesson",
  "MCO": "Moody's Corp.",
  "MDLZ": "Mondelez International",
  "MDT": "Medtronic",
  "MELI": "MercadoLibre",
  "MET": "MetLife",
  "META": "Meta Platforms",
  "MLM": "Martin Marietta",
  "MMM": "3M Company",
  "MNST": "Monster Beverage",
  "MO": "Altria Group",
  "MPC": "Marathon Petroleum",
  "MPWR": "Monolithic Power",
  "MRK": "Merck & Co.",
  "MRNA": "Moderna",
  "MRVL": "Marvell Technology",
  "MS": "Morgan Stanley",
  "MSFT": "Microsoft Corp.",
  "MU": "Micron Technology",
  "NCLH": "Norwegian Cruise Line",
  "NDAQ": "Nasdaq Inc.",
  "NEE": "NextEra Energy",
  "NEM": "Newmont Corp.",
  "NET": "Cloudflare Inc.",
  "NFLX": "Netflix Inc.",
  "NIO": "NIO Inc.",
  "NKE": "Nike Inc.",
  "NOC": "Northrop Grumman",
  "NOK": "Nokia",
  "NOW": "ServiceNow Inc.",
  "NSC": "Norfolk Southern",
  "NTAP": "NetApp",
  "NTES": "NetEase",
  "NU": "Nu Holdings",
  "NUE": "Nucor",
  "NVDA": "NVIDIA Corp.",
  "NVO": "Novo Nordisk",
  "NXPI": "NXP Semiconductors",
  "O": "Realty Income",
  "ODFL": "Old Dominion Freight",
  "ON": "ON Semiconductor",
  "ORCL": "Oracle Corp.",
  "ORLY": "O'Reilly Automotive",
  "OTIS": "Otis Worldwide",
  "OXY": "Occidental Petroleum",
  "PANW": "Palo Alto Networks",
  "PAYX": "Paychex",
  "PBR": "Petr\u00f3leo Brasileiro",
  "PCAR": "PACCAR",
  "PCG": "PG&E Corp.",
  "PDD": "PDD Holdings",
  "PEP": "PepsiCo Inc.",
  "PFE": "Pfizer Inc.",
  "PG": "Procter & Gamble",
  "PH": "Parker-Hannifin",
  "PHG": "Philips",
  "PINS": "Pinterest",
  "PLD": "Prologis Inc.",
  "PLTR": "Palantir Technologies",
  "PLUG": "Plug Power",
  "PM": "Philip Morris",
  "PNC": "PNC Financial",
  "PRU": "Prudential Financial",
  "PSA": "Public Storage",
  "PSX": "Phillips 66",
  "PYPL": "PayPal Holdings",
  "QCOM": "Qualcomm Inc.",
  "QQQ": "Invesco QQQ Trust",
  "QRVO": "Qorvo",
  "RACE": "Ferrari N.V.",
  "RBLX": "Roblox Corp.",
  "RCL": "Royal Caribbean",
  "REGN": "Regeneron Pharmaceuticals",
  "RELX": "RELX plc",
  "RIO": "Rio Tinto",
  "RIOT": "Riot Platforms",
  "RIVN": "Rivian Automotive",
  "ROK": "Rockwell Automation",
  "ROKU": "Roku Inc.",
  "ROST": "Ross Stores",
  "RSG": "Republic Services",
  "RTX": "RTX Corp.",
  "RUN": "Sunrun",
  "RY": "Royal Bank of Canada",
  "SAN": "Banco Santander",
  "SAP": "SAP SE",
  "SBUX": "Starbucks Corp.",
  "SCCO": "Southern Copper",
  "SCHW": "Charles Schwab",
  "SE": "Sea Limited",
  "SHEL": "Shell plc",
  "SHOP": "Shopify",
  "SHW": "Sherwin-Williams",
  "SIEGY": "Siemens",
  "SLB": "Schlumberger",
  "SLV": "iShares Silver Trust",
  "SMCI": "Super Micro Computer",
  "SNAP": "Snap Inc.",
  "SNOW": "Snowflake Inc.",
  "SNPS": "Synopsys Inc.",
  "SNY": "Sanofi",
  "SO": "Southern Company",
  "SOFI": "SoFi Technologies",
  "SONY": "Sony Group",
  "SPG": "Simon Property",
  "SPGI": "S&P Global",
  "SPOT": "Spotify",
  "SPY": "SPDR S&P 500 ETF",
  "SQ": "Block Inc.",
  "SRE": "Sempra",
  "STLA": "Stellantis",
  "STLD": "Steel Dynamics",
  "STT": "State Street",
  "STX": "Seagate Technology",
  "STZ": "Constellation Brands",
  "SU": "Suncor Energy",
  "SWKS": "Skyworks Solutions",
  "SYK": "Stryker",
  "SYY": "Sysco",
  "T": "AT&T Inc.",
  "TAK": "Takeda Pharmaceutical",
  "TD": "Toronto-Dominion Bank",
  "TDG": "TransDigm",
  "TEAM": "Atlassian Corp.",
  "TFC": "Truist Financial",
  "TGT": "Target Corp.",
  "TJX": "TJX Companies",
  "TLT": "iShares 20+ Year Treasury",
  "TM": "Toyota Motor",
  "TME": "Tencent Music",
  "TMO": "Thermo Fisher",
  "TMUS": "T-Mobile US",
  "TRP": "TC Energy",
  "TRU": "TransUnion",
  "TSLA": "Tesla Inc.",
  "TSM": "Taiwan Semiconductor",
  "TT": "Trane Technologies",
  "TTD": "The Trade Desk",
  "TTE": "TotalEnergies",
  "TXN": "Texas Instruments",
  "UAL": "United Airlines",
  "UBER": "Uber Technologies",
  "UBS": "UBS Group",
  "UL": "Unilever",
  "UNH": "UnitedHealth Group",
  "UNP": "Union Pacific",
  "UPS": "United Parcel Service",
  "UPST": "Upstart Holdings",
  "URI": "United Rentals",
  "USB": "U.S. Bancorp",
  "V": "Visa Inc.",
  "VALE": "Vale S.A.",
  "VEEV": "Veeva Systems",
  "VICI": "VICI Properties",
  "VMC": "Vulcan Materials",
  "VOO": "Vanguard S&P 500",
  "VRTX": "Vertex Pharmaceuticals",
  "VTI": "Vanguard Total Stock Market",
  "VZ": "Verizon Communications",
  "WBA": "Walgreens Boots Alliance",
  "WDAY": "Workday",
  "WDC": "Western Digital",
  "WEC": "WEC Energy",
  "WELL": "Welltower",
  "WFC": "Wells Fargo",
  "WIT": "Wipro",
  "WM": "Waste Management",
  "WMT": "Walmart Inc.",
  "X": "United States Steel",
  "XEL": "Xcel Energy",
  "XOM": "Exxon Mobil",
  "XPEV": "XPeng",
  "YUM": "Yum! Brands",
  "ZM": "Zoom Video",
  "ZS": "Zscaler Inc.",
  "ZTS": "Zoetis Inc.",
};

/** Lowercase company keyword → ticker for news/search. */
const NAME_TO_SYMBOL: Record<string, string> = {
  "alphabet": "GOOGL",
  "amazon": "AMZN",
  "apple": "AAPL",
  "asml": "ASML",
  "atlassian": "TEAM",
  "berkshire": "BRK-B",
  "cadence": "CDNS",
  "crowdstrike": "CRWD",
  "facebook": "META",
  "ferrari": "RACE",
  "fortinet": "FTNT",
  "google": "GOOGL",
  "meta": "META",
  "microsoft": "MSFT",
  "nvidia": "NVDA",
  "oracle": "ORCL",
  "palantir": "PLTR",
  "servicenow": "NOW",
  "snowflake": "SNOW",
  "synopsys": "SNPS",
  "tesla": "TSLA",
  "tsmc": "TSM",
  "zscaler": "ZS",
  "amazoncom": "AMZN",
  "meta platforms": "META",
  "broadcom": "AVGO",
  "salesforce": "CRM",
  "adobe": "ADBE",
  "advanced": "AMD",
  "advanced micro": "AMD",
  "intel": "INTC",
  "cisco": "CSCO",
  "ibm": "IBM",
  "qualcomm": "QCOM",
  "texas": "TXN",
  "texas instruments": "TXN",
  "applied": "AMAT",
  "applied materials": "AMAT",
  "lam": "LRCX",
  "lam research": "LRCX",
  "kla": "KLAC",
  "micron": "MU",
  "analog": "ADI",
  "analog devices": "ADI",
  "palo": "PANW",
  "palo alto": "PANW",
  "datadog": "DDOG",
  "cloudflare": "NET",
  "coinbase": "COIN",
  "coinbase global": "COIN",
  "intuit": "INTU",
  "cadence design": "CDNS",
  "workday": "WDAY",
  "hubspot": "HUBS",
  "veeva": "VEEV",
  "accenture": "ACN",
  "adp": "ADP",
  "paychex": "PAYX",
  "cognizant": "CTSH",
  "infosys": "INFY",
  "wipro": "WIT",
  "taiwan": "TSM",
  "taiwan semiconductor": "TSM",
  "arm": "ARM",
  "marvell": "MRVL",
  "on semiconductor": "ON",
  "nxp": "NXPI",
  "nxp semiconductors": "NXPI",
  "microchip": "MCHP",
  "skyworks": "SWKS",
  "skyworks solutions": "SWKS",
  "qorvo": "QRVO",
  "monolithic": "MPWR",
  "monolithic power": "MPWR",
  "arista": "ANET",
  "arista networks": "ANET",
  "dell": "DELL",
  "hewlett": "HPE",
  "hewlett packard": "HPE",
  "western": "WDC",
  "western digital": "WDC",
  "seagate": "STX",
  "netapp": "NTAP",
  "corning": "GLW",
  "keysight": "KEYS",
  "super": "SMCI",
  "super micro": "SMCI",
  "berkshire hathaway": "BRK-B",
  "jpmorgan": "JPM",
  "jpmorgan chase": "JPM",
  "visa": "V",
  "mastercard": "MA",
  "bank of": "BAC",
  "wells": "WFC",
  "wells fargo": "WFC",
  "goldman": "GS",
  "goldman sachs": "GS",
  "morgan": "MS",
  "morgan stanley": "MS",
  "citigroup": "C",
  "american express": "AXP",
  "blackrock": "BLK",
  "charles": "SCHW",
  "charles schwab": "SCHW",
  "sp global": "SPGI",
  "moodys": "MCO",
  "intercontinental": "ICE",
  "intercontinental exchange": "ICE",
  "cme": "CME",
  "paypal": "PYPL",
  "block": "SQ",
  "sofi": "SOFI",
  "robinhood": "HOOD",
  "robinhood markets": "HOOD",
  "affirm": "AFRM",
  "upstart": "UPST",
  "capital": "COF",
  "capital one": "COF",
  "us bancorp": "USB",
  "pnc": "PNC",
  "pnc financial": "PNC",
  "truist": "TFC",
  "truist financial": "TFC",
  "state": "STT",
  "state street": "STT",
  "metlife": "MET",
  "prudential": "PRU",
  "prudential financial": "PRU",
  "allstate": "ALL",
  "fidelity": "FIS",
  "fidelity national": "FIS",
  "fiserv": "FI",
  "global payments": "GPN",
  "transunion": "TRU",
  "nasdaq": "NDAQ",
  "unitedhealth": "UNH",
  "johnson": "JNJ",
  "johnson johnson": "JNJ",
  "eli": "LLY",
  "eli lilly": "LLY",
  "merck": "MRK",
  "abbvie": "ABBV",
  "pfizer": "PFE",
  "thermo": "TMO",
  "thermo fisher": "TMO",
  "abbott": "ABT",
  "abbott laboratories": "ABT",
  "danaher": "DHR",
  "bristol-myers": "BMY",
  "bristol-myers squibb": "BMY",
  "amgen": "AMGN",
  "gilead": "GILD",
  "gilead sciences": "GILD",
  "intuitive": "ISRG",
  "intuitive surgical": "ISRG",
  "vertex": "VRTX",
  "vertex pharmaceuticals": "VRTX",
  "regeneron": "REGN",
  "regeneron pharmaceuticals": "REGN",
  "cvs": "CVS",
  "cvs health": "CVS",
  "elevance": "ELV",
  "elevance health": "ELV",
  "cigna": "CI",
  "humana": "HUM",
  "zoetis": "ZTS",
  "medtronic": "MDT",
  "stryker": "SYK",
  "boston": "BSX",
  "boston scientific": "BSX",
  "edwards": "EW",
  "edwards lifesciences": "EW",
  "dexcom": "DXCM",
  "moderna": "MRNA",
  "biogen": "BIIB",
  "illumina": "ILMN",
  "idexx": "IDXX",
  "idexx laboratories": "IDXX",
  "novo": "NVO",
  "novo nordisk": "NVO",
  "astrazeneca": "AZN",
  "gsk": "GSK",
  "sanofi": "SNY",
  "takeda": "TAK",
  "takeda pharmaceutical": "TAK",
  "walmart": "WMT",
  "costco": "COST",
  "costco wholesale": "COST",
  "home": "HD",
  "home depot": "HD",
  "lowes": "LOW",
  "target": "TGT",
  "tjx": "TJX",
  "nike": "NKE",
  "starbucks": "SBUX",
  "mcdonalds": "MCD",
  "walt": "DIS",
  "walt disney": "DIS",
  "netflix": "NFLX",
  "booking": "BKNG",
  "airbnb": "ABNB",
  "uber": "UBER",
  "marriott": "MAR",
  "chipotle": "CMG",
  "chipotle mexican": "CMG",
  "lululemon": "LULU",
  "lululemon athletica": "LULU",
  "ross": "ROST",
  "ross stores": "ROST",
  "procter": "PG",
  "procter gamble": "PG",
  "coca-cola": "KO",
  "pepsico": "PEP",
  "philip": "PM",
  "philip morris": "PM",
  "altria": "MO",
  "colgate-palmolive": "CL",
  "este": "EL",
  "este lauder": "EL",
  "yum": "YUM",
  "yum brands": "YUM",
  "dominos": "DPZ",
  "dominos pizza": "DPZ",
  "darden": "DRI",
  "darden restaurants": "DRI",
  "etsy": "ETSY",
  "chewy": "CHWY",
  "draftkings": "DKNG",
  "roblox": "RBLX",
  "doordash": "DASH",
  "unilever": "UL",
  "diageo": "DEO",
  "anheuser-busch": "BUD",
  "anheuser-busch inbev": "BUD",
  "constellation": "STZ",
  "constellation brands": "STZ",
  "brown-forman": "BF-B",
  "monster": "MNST",
  "monster beverage": "MNST",
  "keurig": "KDP",
  "keurig dr": "KDP",
  "general mills": "GIS",
  "kellanova": "K",
  "hershey": "HSY",
  "mondelez": "MDLZ",
  "ferrari nv": "RACE",
  "toyota": "TM",
  "toyota motor": "TM",
  "honda": "HMC",
  "honda motor": "HMC",
  "stellantis": "STLA",
  "ford": "F",
  "ford motor": "F",
  "general motors": "GM",
  "rivian": "RIVN",
  "rivian automotive": "RIVN",
  "lucid": "LCID",
  "mobileye": "MBLY",
  "aptiv": "APTV",
  "carnival": "CCL",
  "royal caribbean": "RCL",
  "norwegian": "NCLH",
  "norwegian cruise": "NCLH",
  "delta": "DAL",
  "delta air": "DAL",
  "united airlines": "UAL",
  "american airlines": "AAL",
  "southwest": "LUV",
  "southwest airlines": "LUV",
  "alaska": "ALK",
  "alaska air": "ALK",
  "expedia": "EXPE",
  "lyft": "LYFT",
  "exxon": "XOM",
  "exxon mobil": "XOM",
  "chevron": "CVX",
  "conocophillips": "COP",
  "schlumberger": "SLB",
  "eog": "EOG",
  "eog resources": "EOG",
  "occidental": "OXY",
  "occidental petroleum": "OXY",
  "marathon": "MPC",
  "marathon petroleum": "MPC",
  "phillips": "PSX",
  "phillips 66": "PSX",
  "freeport-mcmoran": "FCX",
  "newmont": "NEM",
  "linde": "LIN",
  "air": "APD",
  "air products": "APD",
  "sherwin-williams": "SHW",
  "ecolab": "ECL",
  "dow": "DOW",
  "dupont": "DD",
  "nucor": "NUE",
  "steel": "STLD",
  "steel dynamics": "STLD",
  "vulcan": "VMC",
  "vulcan materials": "VMC",
  "martin": "MLM",
  "martin marietta": "MLM",
  "shell": "SHEL",
  "totalenergies": "TTE",
  "equinor": "EQNR",
  "canadian natural": "CNQ",
  "suncor": "SU",
  "suncor energy": "SU",
  "enbridge": "ENB",
  "tc energy": "TRP",
  "bhp": "BHP",
  "rio": "RIO",
  "rio tinto": "RIO",
  "vale": "VALE",
  "vale sa": "VALE",
  "southern copper": "SCCO",
  "alcoa": "AA",
  "united states": "X",
  "cleveland-cliffs": "CLF",
  "caterpillar": "CAT",
  "deere": "DE",
  "honeywell": "HON",
  "united parcel": "UPS",
  "rtx": "RTX",
  "lockheed": "LMT",
  "lockheed martin": "LMT",
  "boeing": "BA",
  "ge aerospace": "GE",
  "union": "UNP",
  "union pacific": "UNP",
  "fedex": "FDX",
  "csx": "CSX",
  "norfolk": "NSC",
  "norfolk southern": "NSC",
  "waste": "WM",
  "waste management": "WM",
  "republic": "RSG",
  "republic services": "RSG",
  "emerson": "EMR",
  "emerson electric": "EMR",
  "illinois": "ITW",
  "illinois tool": "ITW",
  "parker-hannifin": "PH",
  "rockwell": "ROK",
  "rockwell automation": "ROK",
  "carrier": "CARR",
  "carrier global": "CARR",
  "otis": "OTIS",
  "otis worldwide": "OTIS",
  "general dynamics": "GD",
  "northrop": "NOC",
  "northrop grumman": "NOC",
  "l3harris": "LHX",
  "transdigm": "TDG",
  "heico": "HEI",
  "axon": "AXON",
  "axon enterprise": "AXON",
  "canadian national": "CNI",
  "canadian pacific": "CP",
  "united rentals": "URI",
  "paccar": "PCAR",
  "cummins": "CMI",
  "att": "T",
  "verizon": "VZ",
  "verizon communications": "VZ",
  "t-mobile": "TMUS",
  "t-mobile us": "TMUS",
  "comcast": "CMCSA",
  "charter": "CHTR",
  "charter communications": "CHTR",
  "nextera": "NEE",
  "nextera energy": "NEE",
  "duke": "DUK",
  "duke energy": "DUK",
  "american electric": "AEP",
  "sempra": "SRE",
  "exelon": "EXC",
  "xcel": "XEL",
  "xcel energy": "XEL",
  "dominion": "D",
  "dominion energy": "D",
  "pge": "PCG",
  "consolidated": "ED",
  "consolidated edison": "ED",
  "wec": "WEC",
  "wec energy": "WEC",
  "eversource": "ES",
  "eversource energy": "ES",
  "mara": "MARA",
  "riot": "RIOT",
  "riot platforms": "RIOT",
  "enphase": "ENPH",
  "enphase energy": "ENPH",
  "first solar": "FSLR",
  "sunrun": "RUN",
  "plug": "PLUG",
  "plug power": "PLUG",
  "chargepoint": "CHPT",
  "trade": "TTD",
  "trade desk": "TTD",
  "pinterest": "PINS",
  "snap": "SNAP",
  "roku": "ROKU",
  "spotify": "SPOT",
  "zoom": "ZM",
  "zoom video": "ZM",
  "shopify": "SHOP",
  "sea": "SE",
  "sea limited": "SE",
  "mercadolibre": "MELI",
  "grab": "GRAB",
  "alibaba": "BABA",
  "jdcom": "JD",
  "pdd": "PDD",
  "baidu": "BIDU",
  "nio": "NIO",
  "xpeng": "XPEV",
  "li auto": "LI",
  "tencent": "TME",
  "tencent music": "TME",
  "bilibili": "BILI",
  "netease": "NTES",
  "sony": "SONY",
  "sap": "SAP",
  "sap se": "SAP",
  "siemens": "SIEGY",
  "philips": "PHG",
  "abb": "ABB",
  "nokia": "NOK",
  "ericsson": "ERIC",
  "relx": "RELX",
  "hsbc": "HSBC",
  "barclays": "BCS",
  "deutsche": "DB",
  "deutsche bank": "DB",
  "ing": "ING",
  "ing groep": "ING",
  "banco": "SAN",
  "banco santander": "SAN",
  "banco bilbao": "BBVA",
  "ubs": "UBS",
  "royal bank": "RY",
  "toronto-dominion": "TD",
  "toronto-dominion bank": "TD",
  "canadian imperial": "CM",
  "icici": "IBN",
  "icici bank": "IBN",
  "hdfc": "HDB",
  "hdfc bank": "HDB",
  "ita": "ITUB",
  "ita unibanco": "ITUB",
  "petrleo": "PBR",
  "petrleo brasileiro": "PBR",
  "banco bradesco": "BBD",
  "prologis": "PLD",
  "american tower": "AMT",
  "equinix": "EQIX",
  "simon": "SPG",
  "simon property": "SPG",
  "realty": "O",
  "realty income": "O",
  "public storage": "PSA",
  "welltower": "WELL",
  "digital": "DLR",
  "digital realty": "DLR",
  "vici": "VICI",
  "vici properties": "VICI",
  "avalonbay": "AVB",
  "avalonbay communities": "AVB",
  "spdr": "SPY",
  "spdr sp": "SPY",
  "invesco": "QQQ",
  "invesco qqq": "QQQ",
  "ishares": "IWM",
  "ishares russell": "IWM",
  "spdr dow": "DIA",
  "vanguard": "VTI",
  "vanguard total": "VTI",
  "vanguard sp": "VOO",
  "ishares msci": "EFA",
  "spdr gold": "GLD",
  "ishares silver": "SLV",
  "ishares 20": "TLT",
  "ishares iboxx": "HYG",
  "crh": "CRH",
  "eaton": "ETN",
  "trane": "TT",
  "johnson controls": "JCI",
  "ingersoll": "IR",
  "ingersoll rand": "IR",
  "ametek": "AME",
  "fastenal": "FAST",
  "ww grainger": "GWW",
  "cintas": "CTAS",
  "old": "ODFL",
  "old dominion": "ODFL",
  "copart": "CPRT",
  "oreilly": "ORLY",
  "oreilly automotive": "ORLY",
  "autozone": "AZO",
  "advance": "AAP",
  "advance auto": "AAP",
  "best": "BBY",
  "best buy": "BBY",
  "dollar": "DG",
  "dollar general": "DG",
  "dollar tree": "DLTR",
  "kroger": "KR",
  "sysco": "SYY",
  "mckesson": "MCK",
  "cardinal": "CAH",
  "cardinal health": "CAH",
  "cencora": "COR",
  "walgreens": "WBA",
  "walgreens boots": "WBA",
};

const TICKER_PATTERN = /\$?([A-Z]{1,5})\b/g;

export function extractTickersFromText(text: string): string[] {
  if (!text) return [];
  const upper = text.toUpperCase();
  const found = new Set<string>();

  for (const match of upper.matchAll(TICKER_PATTERN)) {
    const sym = match[1];
    if (sym && SYMBOL_NAMES[sym]) found.add(sym);
  }

  const lower = text.toLowerCase();
  for (const [name, sym] of Object.entries(NAME_TO_SYMBOL)) {
    if (lower.includes(name)) found.add(sym);
  }

  return [...found].slice(0, 6);
}

export function companyNameFor(symbol: string): string | null {
  return SYMBOL_NAMES[symbol.toUpperCase()] ?? null;
}

/** Resolve a ticker from a company name or symbol query. */
export function resolveSymbolQuery(query: string): string | null {
  const q = query.trim();
  if (!q) return null;
  const upper = q.toUpperCase();
  if (SYMBOL_NAMES[upper]) return upper;
  const lower = q.toLowerCase();
  if (NAME_TO_SYMBOL[lower]) return NAME_TO_SYMBOL[lower];
  for (const [name, sym] of Object.entries(NAME_TO_SYMBOL)) {
    if (name.includes(lower) || lower.includes(name)) return sym;
  }
  for (const [sym, name] of Object.entries(SYMBOL_NAMES)) {
    if (name.toLowerCase().includes(lower)) return sym;
  }
  // Allow any plausible ticker even if not in the static map
  if (/^[A-Z][A-Z0-9.\-]{0,6}$/.test(upper)) return upper;
  return null;
}

